version: '3'
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.docker/php/apache/:/etc/apache2/sites-enabled/
      - ./.docker/php/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 8080:80
    command: ["sh", "-c", "composer install;apache2-foreground"]
    depends_on:
      - mysql
    # platform: linux/x86_64
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: p@ssw0rd
    depends_on:
      - phpmyadmin
    platform: linux/x86_64
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'mysql'
    ports:
      - 18080:80
    # platform: linux/x86_64