version: '3'
services:
  php:
    container_name: php # コンテナ名
    build: # Dockerfileの場所を指定
      context: . # Dockerfileの場所
      dockerfile: ./.docker/php/Dockerfile # Dockerfileのファイル名
    volumes: # ホスト側のディレクトリをコンテナ側にマウント
      - ./:/var/www/html # ホスト側のディレクトリ:コンテナ側のディレクトリ
      - ./.docker/php/apache/:/etc/apache2/sites-enabled/ # ホスト側のディレクトリ:コンテナ側のディレクトリ
      - ./.docker/php/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # ホスト側のディレクトリ:コンテナ側のディレクトリ
    ports: # ホスト側のポート:コンテナ側のポート
      - 8080:80 # ホスト側のポート:コンテナ側のポート
    command: ["sh", "-c", "composer install;apache2-foreground"] # コンテナ起動時に実行するコマンド
    depends_on: # コンテナ起動時に依存するコンテナを指定
      - mysql # コンテナ名
    # platform: linux/x86_64
  mysql: # コンテナ名
    container_name: mysql # コンテナ名
    image: mysql:8.0 # イメージ名
    volumes: # ホスト側のディレクトリをコンテナ側にマウント
      - ./.data/mysql:/var/lib/mysql # ホスト側のディレクトリ:コンテナ側のディレクトリ
    ports: # ホスト側のポート:コンテナ側のポート
      - "3306:3306" # ホスト側のポート:コンテナ側のポート
    environment: # 環境変数を指定
      MYSQL_ROOT_PASSWORD: rootpw # DBルートユーザのパスワード
      MYSQL_DATABASE: develop # データベース名
      MYSQL_USER: develop # DBユーザ名
      MYSQL_PASSWORD: p@ssw0rd # DBユーザパスワード
    depends_on: # コンテナ起動時に依存するコンテナを指定
      - phpmyadmin # コンテナ名
    # platform: linux/x86_64 # プラットフォームを指定
  phpmyadmin: # コンテナ名
    container_name: phpmyadmin # コンテナ名
    image: phpmyadmin/phpmyadmin:latest # イメージ名
    environment: # 環境変数を指定
      PMA_HOST: 'mysql' #DBサーバのホスト名
    ports: # ポートフォワーディング ホスト側のポート:コンテナ側のポート
      - 18080:80 # ホスト側のポート:コンテナ側のポート
    # platform: linux/x86_64